---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product-service
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helmcharts/product-service
      reconcileStrategy: Revision
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: helmcharts-repo-production
        namespace: flux-system
      valuesFiles:
        - ./helmcharts/product-service/values.yaml
  targetNamespace: production
  releaseName: product-service
  interval: 24h
  timeout: 5m
