---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product-review
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./product-review
      reconcileStrategy: Revision
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: helmcharts-repo
        namespace: flux-system
      valuesFiles:
        - ./product-review/values.yaml
  targetNamespace: production
  releaseName: product-review
  interval: 24h
  timeout: 5m
