---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helmcharts-repo
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: dev
  url: ssh://git@github.com:ktaf/product-manage-challenge/helm-charts
  secretRef:
    name: product-manage-challenge-repo
