apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product-review
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helmcharts/product-review
      reconcileStrategy: Revision
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: helmcharts-repo-staging
        namespace: flux-system
      valuesFiles:
        - ./helmcharts/product-review/values.yaml
        - ./helmcharts/product-review/values-staging.yaml
  test:
    enable: true
  targetNamespace: staging
  releaseName: product-review
  interval: 30m
  timeout: 5m
