---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product-service
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./product-service
      reconcileStrategy: Revision
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: helmcharts-repo
        namespace: flux-system
      valuesFiles:
        - ./product-service/values.yaml
  test:
    enable: true
  targetNamespace: staging
  releaseName: product-service
  interval: 30m
  timeout: 5m
