apiVersion: v1
kind: Service
metadata:
  name: product-review
  labels:
    {{- include "product-review.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "product-review.selectorLabels" . | nindent 4 }}
